export const ELEMENTS = { 
  inputSignupName: 'input[data-qa=signup-name]',
  inputEmail: 'input[data-qa=signup-email]',
  inputName: 'input[data-qa=name]',
  inputPassword: 'input[data-qa=password]',
  buttonSignUp: 'button[data-qa=signup-button]',
  inputGender: '#id_gender1',
  selectDay: 'select[data-qa=days]',
  selectMonth: 'select[data-qa=months]',
  selectYears: 'select[data-qa=years]',
  inputFirtstName: 'input[data-qa=first_name]',
  inputLastName: 'input[data-qa=last_name]',
  inputCompany: 'input[data-qa=company]',
  inputAddress: 'input[data-qa=address]',
  selectCountry: 'select[data-qa=country]',
  inputState: 'input[data-qa=state]',
  inputCity: 'input[data-qa=city]',
  inputZipCode: 'input[data-qa=zipcode]',
  inputMobileNumber: 'input[data-qa=mobile_number]',
  buttonCreateAccount: 'button[data-qa=create-account]',
};